name: Run UI Tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: c7toc5154/test_image:latest

    - name: Run UI tests
      run: |
        docker-compose up --build --exit-code-from pytest pytest -m "ui_checkup"
        docker-compose down
