name: Run UI Tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and run tests
      run: |
        docker-compose up -d
        docker-compose run --rm pytest pytest -m "ui_checkup"
        docker-compose down

