name: Automated Tests Workflow

on: push
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Clone Repository
        run: git clone https://github.com/gateway-fm/autotests.git

#      - name: Install Dependencies
#        run: |
#          cd <название_склонированной_папки>
#          pip install -r requirements.txt

      - name: Run Automated Tests
        run: |
          docker-compose run pytest pytest -m "unit" --alluredir=allure-results || FAILED=true
