name: UI Autotests

on: push
#  push:
#    branches:
#      - main

jobs:

  run-ui-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull Docker image
      run: docker pull c7toc5154/autotests:latest

    - name: Install dependencies
      run: |
        docker run -v ${{ github.workspace }}:/app c7toc5154/autotests:latest pip install -r requirements.txt

    - name: Run UI tests
      run: |
        docker run -v ${{ github.workspace }}:/app c7toc5154/autotests:latest pytest -m "ui" --alluredir=allure-results

    - name: Store allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results
        retention-days: 1
