name: UI Autotests

on: push

jobs:

  run-ui-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull Docker image
      run: docker pull c7toc5154/test_image:latest

    - name: Build Docker image
      run: docker build . -t c7toc5154/test_image:latest -f Dockerfile

    - name: Run tests with Docker Compose
      run: |
        docker-compose up --build --exit-code-from pytest pytest -m "ui_checkup" 
        docker-compose down
        
    - name: Store allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results
        retention-days: 1
