name: Run UI Tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:

    - name: Build and run tests
      run: |
        docker-compose up --build --exit-code-from pytest pytest -m "ui_checkup"
        docker-compose down
